# Generated by Django 5.0.6 on 2024-05-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_alter_carte_date_exp_alter_client_num_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='carte',
        ),
        migrations.AddField(
            model_name='carte',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scm.client'),
        ),
    ]
