# Generated by Django 5.0.6 on 2024-05-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0003_remove_client_carte_carte_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
