# Generated by Django 5.0.6 on 2024-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0005_alter_carte_date_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
